### ISSUE TITLE
can't add my MangaDex account in the MangaDex Settings

### ISSUE THREAD

**Issue by EdwardGrave** [nekomangaorg/Neko#1642]
### Steps to reproduce

1. Open Neko and go to mangadex settings
2. tap mangadex login
3. Enter user info, login
4. returns to the app
5. get error could not login
![WhatsApp Image 2024-01-14 at 01 44 03_dc6001d8](https://github.com/nekomangaorg/Neko/assets/32829453/814d7c19-60fa-4bec-93f9-8fb2de4c4ac4)

### Expected behavior

Should login

### Actual behavior

returned error

### Crash logs

[neko_crash_logs[1].txt](https://github.com/nekomangaorg/Neko/files/13930841/neko_crash_logs.1.txt)

### Neko version

2.14.2

### Android version

Android 12

### Device

Samsung S10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Can you verify you can login to the site and your account isn't locked. Usually this is an issue with your account on mangadex

**Comment by EdwardGrave** [comment]
![image](https://github.com/nekomangaorg/Neko/assets/32829453/a8f6e7b3-bd71-4977-ae33-34ce97015340)

**Comment by nonproto** [comment]
Not seeing anything in the error log, did you confirm your account when you created it from mangadex? Sometimes the email confirmation isn't done and prevents access.

**Comment by EdwardGrave** [comment]
this isn't a new account, I've been using mangadex for years

**Comment by BraveDude8** [comment]
Does logging into MD from an incognito tab and creating a brand new login session work?

**Comment by EdwardGrave** [comment]
I tried uninstalling and then installing again, but again, I go in, go into login, put my info, returns to the app and then the app gives the error

**Comment by nonproto** [comment]
Can you enable debug logging in the advanced settings, force close, try to login, then reattach the logs.

**Comment by EdwardGrave** [comment]
do you mean verbose logging?

**Comment by EdwardGrave** [comment]
[neko_crash_logs2.txt](https://github.com/nekomangaorg/Neko/files/13932436/neko_crash_logs2.txt)
I think this is correct?

**Comment by nonproto** [comment]
```
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: java.io.IOException: Unable to parse TLS packet header
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at eu.kanade.tachiyomi.source.online.MangaDexLoginHelper.login(SourceFile:170)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at eu.kanade.tachiyomi.ui.setting.logins.MangaDexLoginActivity$handleResult$1.invokeSuspend(Unknown Source:36)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: Caused by: javax.net.ssl.SSLException: Unable to parse TLS packet header
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:807)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.connection.ConnectPlan.connectTls(Unknown Source:39)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.connection.ConnectPlan.connectTlsEtc(Unknown Source:227)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.connection.FastFallbackExchangeFinder.find(Unknown Source:114)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(Unknown Source:29)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown Source:11)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:160)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.cache.CacheInterceptor.intercept(Unknown Source:181)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:160)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.http.BridgeInterceptor.intercept(Unknown Source:170)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:160)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown Source:34)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:160)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(SourceFile:593)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:160)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at org.nekomanga.core.network.interceptor.HeadersInterceptor.intercept(Unknown Source:87)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:160)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(SourceFile:593)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:160)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at org.nekomanga.core.network.interceptor.RateLimitInterceptor.intercept(Unknown Source:34)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:160)
01-14 10:05:20.000 11305 11383 E (SourceFile:257)#login: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(Unknown Source:116)
```

**Comment by nonproto** [comment]
Based off that error, I dunno.  I obviously am not having an issue, it could be rom/browser related.  Try using chrome?

**Comment by christantoan** [comment]
Same here as well. Logs attached using Chrome when logging in.
[neko_crash_logs.txt](https://github.com/nekomangaorg/Neko/files/14266909/neko_crash_logs.txt)

**Comment by nonproto** [comment]
@BraveDude8 then latest logs has `HTTP FAILED: java.net.UnknownHostException: auth.mangadex.org: SERVFAIL`

**Comment by christantoan** [comment]
> @BraveDude8 then latest logs has `HTTP FAILED: java.net.UnknownHostException: auth.mangadex.org: SERVFAIL`

Same on mine as well. I ended resetting Neko to solve the problem.

**Comment by christantoan** [comment]
Looks like the issue is DoH. I got this problem again after resetting and setting up my Neko installation.

**Comment by nonproto** [comment]
@EdwardGrave did you try changing DoH?
