### ISSUE TITLE
Crashes whenever you do anything

### ISSUE THREAD

**Issue by Nagifan** [nekomangaorg/Neko#1858]
### Steps to reproduce

Click on anything except for the buttons on the bottom

### Expected behavior

It working

### Actual behavior

![Screenshot_20240627-163315](https://github.com/nekomangaorg/Neko/assets/174064631/131a337e-0e66-45dc-9e1f-203c69d4ffc2)

### Crash logs

App version: 2.16.8 (standard, f928b2950, 8, 2024-06-27T19:00:09.353600783)
Android version: 14 (SDK 34)
Android build ID: AP21.240305.006
Device brand: google
Device manufacturer: Google
Device name: oriole
Device model: Pixel 6
Device product name: oriole_beta
           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: java.lang.IllegalStateException: CompositionLocal LocalLifecycleOwner not present
at androidx.lifecycle.compose.LocalLifecycleOwnerKt$LocalLifecycleOwner$1$1.invoke(SourceFile:9)
at kotlin.SynchronizedLazyImpl.getValue(Unknown Source:20)
at androidx.compose.material3.ButtonKt.read(SourceFile:35)
at androidx.compose.runtime.ComposerImpl.consume(SourceFile:1)
at coil.util.-Logs.collectAsStateWithLifecycle(SourceFile:11)
at eu.kanade.tachiyomi.ui.manga.MangaDetailController.ScreenContent(SourceFile:36)
at eu.kanade.tachiyomi.ui.base.controller.BaseComposeController$onViewCreated$1$1.invoke(SourceFile:2)
at eu.kanade.tachiyomi.ui.base.controller.BaseComposeController$onViewCreated$1$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
at coil.request.Svgs.CompositionLocalProvider(SourceFile:24)
at androidx.compose.material3.TextKt.ProvideTextStyle(SourceFile:76)
at androidx.compose.material3.BadgeKt$Badge$1$1.invoke(SourceFile:89)
at androidx.compose.material3.BadgeKt$Badge$1$1.invoke(SourceFile:12)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
at coil.request.Svgs.CompositionLocalProvider(SourceFile:47)
at androidx.compose.material3.ButtonKt.MaterialTheme(SourceFile:315)
at org.nekomanga.presentation.theme.ThemeKt.NekoTheme(SourceFile:80)
at eu.kanade.tachiyomi.ui.base.controller.BaseComposeController$onViewCreated$1.invoke(SourceFile:2)
at eu.kanade.tachiyomi.ui.base.controller.BaseComposeController$onViewCreated$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at androidx.compose.ui.platform.ComposeView.Content(SourceFile:25)
at ToolTipComponentsKt$ToolTipButton$2$1.invoke(SourceFile:76)
at ToolTipComponentsKt$ToolTipButton$2$1.invoke(SourceFile:16)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
at coil.request.Svgs.CompositionLocalProvider(SourceFile:47)
at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(SourceFile:263)
at androidx.compose.material.ButtonKt$Button$3.invoke(SourceFile:26)
at androidx.compose.material.ButtonKt$Button$3.invoke(SourceFile:9)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
at coil.request.Svgs.CompositionLocalProvider(SourceFile:47)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(SourceFile:458)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:5)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
at coil.request.Svgs.CompositionLocalProvider(SourceFile:24)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:14)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:2)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at androidx.compose.material3.ButtonKt.invokeComposable(SourceFile:1)
at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:119)
at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(SourceFile:11)
at androidx.compose.runtime.CompositionImpl.composeContent(SourceFile:34)
at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(SourceFile:35)
at androidx.compose.runtime.CompositionImpl.composeInitial(SourceFile:1)
at androidx.compose.runtime.CompositionImpl.setContent(Unknown Source:2)
at androidx.compose.runtime.Latch$await$2$2.invoke(SourceFile:142)
at androidx.compose.ui.platform.WrappedComposition.setContent(SourceFile:16)
at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Unknown Source:18)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(SourceFile:32)
at androidx.lifecycle.LifecycleRegistry.addObserver(SourceFile:241)
at androidx.compose.runtime.Latch$await$2$2.invoke(SourceFile:138)
at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(SourceFile:103)
at android.view.View.dispatchAttachedToWindow(View.java:22662)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3495)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
at android.view.ViewGroup.addViewInner(ViewGroup.java:5338)
at android.view.ViewGroup.addView(ViewGroup.java:5124)
at android.view.ViewGroup.addView(ViewGroup.java:5064)
at android.view.ViewGroup.addView(ViewGroup.java:5036)
at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.performChange(Unknown Source:34)
at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(SourceFile:189)
at com.bluelinelabs.conductor.Router.performControllerChange(SourceFile:13)
at com.bluelinelabs.conductor.Router.performControllerChange(SourceFile:4)
at com.bluelinelabs.conductor.Router.pushController(Unknown Source:13)
at eu.kanade.tachiyomi.ui.library.LibraryController.onItemClick(SourceFile:69)
at eu.davidea.viewholders.FlexibleViewHolder.onClick(Unknown Source:51)
at android.view.View.performClick(View.java:7931)
at android.view.View.performClickInternal(View.java:7908)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:30989)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8592)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

           ******************************************************************************************************************************************************************************************************************************
           ******************************************************************************************************************************************************************************************************************************--------- beginning of crash
06-27 16:29:37.306  8013  8013 E AndroidRuntime: FATAL EXCEPTION: main
06-27 16:29:37.306  8013  8013 E AndroidRuntime: Process: org.nekomanga.neko, PID: 8013
06-27 16:29:37.306  8013  8013 E AndroidRuntime: java.lang.IllegalStateException: CompositionLocal LocalLifecycleOwner not present
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.lifecycle.compose.LocalLifecycleOwnerKt$LocalLifecycleOwner$1$1.invoke(SourceFile:9)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(Unknown Source:20)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.material3.ButtonKt.read(SourceFile:35)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.consume(SourceFile:1)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at coil.util.-Logs.collectAsStateWithLifecycle(SourceFile:11)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.MangaDetailController.ScreenContent(SourceFile:36)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseComposeController$onViewCreated$1$1.invoke(SourceFile:2)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseComposeController$onViewCreated$1$1.invoke(SourceFile:1)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at coil.request.Svgs.CompositionLocalProvider(SourceFile:24)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.material3.TextKt.ProvideTextStyle(SourceFile:76)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.material3.BadgeKt$Badge$1$1.invoke(SourceFile:89)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.material3.BadgeKt$Badge$1$1.invoke(SourceFile:12)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at coil.request.Svgs.CompositionLocalProvider(SourceFile:47)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.material3.ButtonKt.MaterialTheme(SourceFile:315)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at org.nekomanga.presentation.theme.ThemeKt.NekoTheme(SourceFile:80)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseComposeController$onViewCreated$1.invoke(SourceFile:2)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseComposeController$onViewCreated$1.invoke(SourceFile:1)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.ui.platform.ComposeView.Content(SourceFile:25)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at ToolTipComponentsKt$ToolTipButton$2$1.invoke(SourceFile:76)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at ToolTipComponentsKt$ToolTipButton$2$1.invoke(SourceFile:16)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at coil.request.Svgs.CompositionLocalProvider(SourceFile:47)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(SourceFile:263)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.material.ButtonKt$Button$3.invoke(SourceFile:26)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.material.ButtonKt$Button$3.invoke(SourceFile:9)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at coil.request.Svgs.CompositionLocalProvider(SourceFile:47)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(SourceFile:458)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:5)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:1)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at coil.request.Svgs.CompositionLocalProvider(SourceFile:24)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:14)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:2)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.material3.ButtonKt.invokeComposable(SourceFile:1)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:119)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(SourceFile:11)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.composeContent(SourceFile:34)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(SourceFile:35)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.composeInitial(SourceFile:1)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.setContent(Unknown Source:2)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.Latch$await$2$2.invoke(SourceFile:142)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition.setContent(SourceFile:16)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Unknown Source:18)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(SourceFile:32)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.addObserver(SourceFile:241)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.runtime.Latch$await$2$2.invoke(SourceFile:138)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(SourceFile:103)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:22662)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3495)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5338)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:5124)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:5064)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:5036)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.performChange(Unknown Source:34)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(SourceFile:189)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(SourceFile:13)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(SourceFile:4)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.pushController(Unknown Source:13)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.recents.RecentsController.onCoverClick(Unknown Source:57)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.recents.RecentMangaHolder$$ExternalSyntheticLambda0.onClick(SourceFile:41)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.view.View.performClick(View.java:7931)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7908)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30989)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8592)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
06-27 16:29:37.306  8013  8013 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: FATAL EXCEPTION: main
06-27 16:29:47.205  8438  8438 E AndroidRuntime: Process: org.nekomanga.neko, PID: 8438
06-27 16:29:47.205  8438  8438 E AndroidRuntime: java.lang.IllegalStateException: CompositionLocal LocalLifecycleOwner not present
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at androidx.lifecycle.compose.LocalLifecycleOwnerKt$LocalLifecycleOwner$1$1.invoke(SourceFile:9)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(Unknown Source:20)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at androidx.compose.material3.ButtonKt.read(SourceFile:35)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.consume(SourceFile:1)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at coil.util.-Logs.collectAsStateWithLifecycle(SourceFile:11)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.MangaDetailController.ScreenContent(SourceFile:36)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseComposeController$onViewCreated$1$1.invoke(SourceFile:2)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseComposeController$onViewCreated$1$1.invoke(SourceFile:1)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at coil.request.Svgs.CompositionLocalProvider(SourceFile:24)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at androidx.compose.material3.TextKt.ProvideTextStyle(SourceFile:76)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at androidx.compose.material3.BadgeKt$Badge$1$1.invoke(SourceFile:89)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at androidx.compose.material3.BadgeKt$Badge$1$1.invoke(SourceFile:12)
06-27 16:29:47.205  8438  8438 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
06-27 16:29:47

### Neko version

2.16.8

### Android version

Android 14

### Device

Google Pixel 6

### Other details

It does this for about everything. Whenever you click on a title or try to search for anything.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
#1857

**Comment by Nagifan** [comment]
> #1857

Different issue. It crashes when you click on anything related to a manga. Latest updates (crash), downloaded manga (crash), titles in your history (crash), if it's not the setting menu or clicking between tabs it crashes. It goes to show you didn't even read my report or 1857s (his was about the about page in particular mine is about literally everything) before deciding to close it. The issue is still there and is not resolved. The app is literally unusable and as far as I can tell there is no way to roll it back. I have taken every step an end user can do such as clearing the cache, restarting the application among others to no solution. The newest update quite literally broke the entire app. I won't pretend like I understand how all this works but does nobody test updates before rolling them out?

**Comment by nonproto** [comment]
You didn't read the crash logs for all the issues. They are all the same. As soon as I get a chance I'll put out a release.  If you can't wait up to a day then feel free to use another app

**Comment by nonproto** [comment]
Also regarding the testing. I don't expect standard library updates to break the entire app. Google released a version of a library that requires a stable release of another library that isn't out yet. Which is a bit ridiculous

**Comment by nonproto** [comment]
fixed in 2.16.9  you may need to manually update

**Comment by Nagifan** [comment]
I'm sorry if I came off as angry in my reply. I don't really understand GitHub nor how bug reporting works on this site. It appeared to me at the time that mine and the previous threads issues were separate because I had different symptoms than they did. I was mostly curious about all this but upon reflection I worded my reply a bit angrily and I'm sorry for that.

**Comment by nonproto** [comment]
All good
