### ISSUE TITLE
An unexpected error

### ISSUE THREAD

**Issue by Johnric419** [nekomangaorg/Neko#1865]
### Steps to reproduce

I just click the search button and then this pop up 
![Screenshot_20240629-074902](https://github.com/nekomangaorg/Neko/assets/174157042/4e7174f3-3a08-4fc0-b819-585d4b9c8fa1)

### Expected behavior

I should expect the app to open up a menu of things you can search on the app like genre and sorting the manga

### Actual behavior

This error message pops up
![Screenshot_20240629-074902](https://github.com/nekomangaorg/Neko/assets/174157042/f403ac12-c63d-4394-851b-410fe8508ead)

### Crash logs

App version: 2.16.9 (standard, b6d958781, 10, 2024-06-28T00:51:12.841592104)
Android version: 12 (SDK 31)
Android build ID: X6815B-H772AB-S-OP-231020V486
Device brand: Infinix
Device manufacturer: INFINIX MOBILITY LIMITED
Device name: Infinix-X6815B
Device model: Infinix X6815B
Device product name: X6815B-OP
           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: kotlinx.serialization.SerializationException: eu.kanade.tachiyomi.source.model.MangaTag does not contain element with name 'ECCHI' at path $.tags[16].tag
at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow(Unknown Source:63)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeEnum(Unknown Source:33)
at kotlinx.serialization.internal.EnumSerializer.deserialize(SourceFile:1)
at kotlinx.serialization.internal.EnumSerializer.deserialize(SourceFile:2)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(Unknown Source:119)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(Unknown Source:10)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:32)
at org.nekomanga.domain.filter.Filter$Tag$$serializer.deserialize(SourceFile:3)
at org.nekomanga.domain.filter.Filter$Tag$$serializer.deserialize(SourceFile:1)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(Unknown Source:119)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(Unknown Source:10)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:32)
at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Unknown Source:7)
at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(Unknown Source:17)
at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(Unknown Source:7)
at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(Unknown Source:63)
at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(Unknown Source:6)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(Unknown Source:119)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(Unknown Source:10)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:32)
at org.nekomanga.domain.filter.DexFilters$$serializer.deserialize(SourceFile:3)
at org.nekomanga.domain.filter.DexFilters$$serializer.deserialize(SourceFile:1)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(Unknown Source:119)
at kotlinx.serialization.json.Json.decodeFromString(SourceFile:2)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1$nameOfEnabledFilter$2.invoke(SourceFile:2)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1$nameOfEnabledFilter$2.invoke(SourceFile:3)
at coil.size.-Sizes.rememberSaveable(SourceFile:87)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1.invoke(SourceFile:19)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
at coil.request.Svgs.CompositionLocalProvider(SourceFile:24)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt.FilterBrowseSheet-gKLzdoI(SourceFile:2)
at org.nekomanga.presentation.screens.browse.BrowseBottomSheetKt.BrowseBottomSheet(SourceFile:460)
at org.nekomanga.presentation.screens.BrowseScreenKt$BrowseScreen$4$1.invoke(SourceFile:22)
at org.nekomanga.presentation.screens.BrowseScreenKt$BrowseScreen$4$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:3)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:14)
at androidx.compose.material.ScaffoldKt$Scaffold$1.invoke(SourceFile:22)
at androidx.compose.material.ScaffoldKt$Scaffold$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:85)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(SourceFile:49)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(SourceFile:2)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
at coil.request.Svgs.CompositionLocalProvider(SourceFile:47)
at coil.size.-Sizes.Surface-F-jzlyU(SourceFile:373)
at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$2.invoke(SourceFile:406)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:3)
at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(SourceFile:36)
at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(SourceFile:4)
at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(SourceFile:490)
at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(SourceFile:58)
at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:156)
at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(SourceFile:29)
at androidx.compose.runtime.CompositionImpl.recompose(SourceFile:34)
at androidx.compose.runtime.Recomposer.access$performRecompose(SourceFile:100)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(SourceFile:404)
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(Unknown Source:8)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(SourceFile:48)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1127)
at android.view.Choreographer.doCallbacks(Choreographer.java:918)
at android.view.Choreographer.doFrame(Choreographer.java:824)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1112)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:241)
at android.os.Looper.loop(Looper.java:342)
at android.app.ActivityThread.main(ActivityThread.java:8118)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@3c28b3f, androidx.compose.ui.platform.MotionDurationScaleImpl@1fcac0c, StandaloneCoroutine{Cancelling}@2491955, AndroidUiDispatcher@b95df6a]

           ******************************************************************************************************************************************************************************************************************************
           ******************************************************************************************************************************************************************************************************************************

### Neko version

2.16.9

### Android version

Android 12

### Device

Infinix ZERO 5G (2022 version)

### Other details

I don't have any details but I'm just gonna explain it again

I decided to click on the search button and the menu did not pop up but instead an error message pop up
![Screenshot_20240629-074902](https://github.com/nekomangaorg/Neko/assets/174157042/39c5dc33-c724-4c17-befd-f95ed3946bf7)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
#1861
