### ISSUE TITLE
Crash when clicking "search" in the browse tab

### ISSUE THREAD

**Issue by Kiesman** [nekomangaorg/Neko#1873]
### Steps to reproduce

1. Click browse
2. Click search

### Expected behavior

Should be able to search

### Actual behavior

Neko crashes. 

### Crash logs

App version: 2.16.9 (standard, b6d958781, 10, 2024-06-28T00:51:12.841592104)
Android version: 14 (SDK 34)
Android build ID: AP2A.240605.024
Device brand: google
Device manufacturer: Google
Device name: panther
Device model: Pixel 7
Device product name: panther
           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: kotlinx.serialization.SerializationException: eu.kanade.tachiyomi.source.model.MangaTag does not contain element with name 'ECCHI' at path $.tags[16].tag
at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow(Unknown Source:63)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeEnum(Unknown Source:33)
at kotlinx.serialization.internal.EnumSerializer.deserialize(SourceFile:1)
at kotlinx.serialization.internal.EnumSerializer.deserialize(SourceFile:2)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(Unknown Source:119)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(Unknown Source:10)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:32)
at org.nekomanga.domain.filter.Filter$Tag$$serializer.deserialize(SourceFile:3)
at org.nekomanga.domain.filter.Filter$Tag$$serializer.deserialize(SourceFile:1)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(Unknown Source:119)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(Unknown Source:10)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:32)
at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Unknown Source:7)
at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(Unknown Source:17)
at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(Unknown Source:7)
at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(Unknown Source:63)
at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(Unknown Source:6)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(Unknown Source:119)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(Unknown Source:10)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:32)
at org.nekomanga.domain.filter.DexFilters$$serializer.deserialize(SourceFile:3)
at org.nekomanga.domain.filter.DexFilters$$serializer.deserialize(SourceFile:1)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(Unknown Source:119)
at kotlinx.serialization.json.Json.decodeFromString(SourceFile:2)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1$nameOfEnabledFilter$2.invoke(SourceFile:2)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1$nameOfEnabledFilter$2.invoke(SourceFile:3)
at coil.size.-Sizes.rememberSaveable(SourceFile:87)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1.invoke(SourceFile:19)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
at coil.request.Svgs.CompositionLocalProvider(SourceFile:24)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt.FilterBrowseSheet-gKLzdoI(SourceFile:2)
at org.nekomanga.presentation.screens.browse.BrowseBottomSheetKt.BrowseBottomSheet(SourceFile:460)
at org.nekomanga.presentation.screens.BrowseScreenKt$BrowseScreen$4$1.invoke(SourceFile:22)
at org.nekomanga.presentation.screens.BrowseScreenKt$BrowseScreen$4$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:3)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:14)
at androidx.compose.material.ScaffoldKt$Scaffold$1.invoke(SourceFile:22)
at androidx.compose.material.ScaffoldKt$Scaffold$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:85)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(SourceFile:49)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(SourceFile:2)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
at coil.request.Svgs.CompositionLocalProvider(SourceFile:47)
at coil.size.-Sizes.Surface-F-jzlyU(SourceFile:373)
at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$2.invoke(SourceFile:406)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:3)
at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(SourceFile:36)
at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(SourceFile:4)
at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(SourceFile:490)
at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(SourceFile:58)
at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:156)
at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(SourceFile:29)
at androidx.compose.runtime.CompositionImpl.recompose(SourceFile:34)
at androidx.compose.runtime.Recomposer.access$performRecompose(SourceFile:100)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(SourceFile:404)
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(Unknown Source:8)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(SourceFile:48)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
at android.view.Choreographer.doFrame(Choreographer.java:941)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8592)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@9644183, androidx.compose.ui.platform.MotionDurationScaleImpl@9f7ff00, StandaloneCoroutine{Cancelling}@849c339, AndroidUiDispatcher@7f9ad7e]

           ******************************************************************************************************************************************************************************************************************************
           ******************************************************************************************************************************************************************************************************************************--------- beginning of main
07-01 09:53:40.163 30788 30808 D SessionLifecycleClient: Sending lifecycle 1 to service
07-01 09:53:40.164 30788 30886 D SessionLifecycleService: Activity foregrounding at 196101732.
07-01 09:53:42.813 30788 30812 W Sensors : Cannot get virtualdevice_native service
07-01 09:53:42.833 30788 30788 I .nekomanga.neko: System.exit called, status: 0
07-01 09:53:42.833 30788 30788 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
07-01 09:53:42.942 31344 31344 I o:error_handler: Using CollectorTypeCMC GC.
07-01 09:53:42.944 31344 31344 E o:error_handler: Not starting debugger since process cannot load the jdwp agent.
07-01 09:53:42.952 31344 31344 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10404; state: ENABLED
07-01 09:53:42.952 31344 31344 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10404; state: ENABLED
07-01 09:53:42.983 31344 31344 D nativeloader: Configuring clns-4 for other apk /data/app/~~28i-LXFSmsgbhQ6GFnrqOw==/org.nekomanga.neko-2qI4gdaDIBkZWWf86QIlxQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~28i-LXFSmsgbhQ6GFnrqOw==/org.nekomanga.neko-2qI4gdaDIBkZWWf86QIlxQ==/lib/arm64:/data/app/~~28i-LXFSmsgbhQ6GFnrqOw==/org.nekomanga.neko-2qI4gdaDIBkZWWf86QIlxQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/org.nekomanga.neko
07-01 09:53:42.992 31344 31344 I MultiDex: VM with version 2.1.0 has multidex support
07-01 09:53:42.992 31344 31344 I MultiDex: Installing application
07-01 09:53:42.992 31344 31344 I MultiDex: VM has multidex support, MultiDex support library is disabled.
07-01 09:53:42.994 31344 31344 W ziparchive: Unable to open '/data/app/~~pYQCJZhsdSk2woDBWuNHfg==/com.google.android.trichromelibrary_647813433-GaBJyiSwFS3ym1QTjrme0Q==/base.dm': No such file or directory
07-01 09:53:42.994 31344 31344 W ziparchive: Unable to open '/data/app/~~pYQCJZhsdSk2woDBWuNHfg==/com.google.android.trichromelibrary_647813433-GaBJyiSwFS3ym1QTjrme0Q==/base.dm': No such file or directory
07-01 09:53:42.994 31344 31344 W o:error_handler: Entry not found
07-01 09:53:42.995 31344 31344 D nativeloader: Configuring clns-5 for other apk /data/app/~~pYQCJZhsdSk2woDBWuNHfg==/com.google.android.trichromelibrary_647813433-GaBJyiSwFS3ym1QTjrme0Q==/base.apk. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/lib/arm64:/data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/base.apk!/lib/arm64-v8a:/data/app/~~pYQCJZhsdSk2woDBWuNHfg==/com.google.android.trichromelibrary_647813433-GaBJyiSwFS3ym1QTjrme0Q==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
07-01 09:53:42.995 31344 31344 D nativeloader: Extending system_exposed_libraries: libedgetpu_dba.google.so
07-01 09:53:42.999 31344 31344 D nativeloader: Configuring clns-6 for other apk /data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/lib/arm64:/data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/base.apk!/lib/arm64-v8a:/data/app/~~pYQCJZhsdSk2woDBWuNHfg==/com.google.android.trichromelibrary_647813433-GaBJyiSwFS3ym1QTjrme0Q==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
07-01 09:53:43.002 31344 31344 I WebViewFactory: Loading com.google.android.webview version 126.0.6478.134 (code 647813433)
07-01 09:53:43.018 31344 31344 I cr_WVCFactoryProvider: version=126.0.6478.134 (647813433) minSdkVersion=29 isBundle=true multiprocess=true packageId=2
07-01 09:53:43.024 31344 31379 E chromium: [0701/095343.024497:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
07-01 09:53:43.028 31344 31344 I cr_LibraryLoader: Successfully loaded native library
07-01 09:53:43.028 31344 31344 I cr_CachingUmaRecorder: Flushed 6 samples from 6 histograms, 0 samples were dropped.
07-01 09:53:43.056 31344 31344 W Iconics : At least one font needs to be registered first
07-01 09:53:43.056 31344 31344 W Iconics :     via com.mikepenz.iconics.Iconics.registerFont(Iconics.kt:117)
07-01 09:53:43.078 31344 31396 D vulkan  : searching for layers in '/data/app/~~28i-LXFSmsgbhQ6GFnrqOw==/org.nekomanga.neko-2qI4gdaDIBkZWWf86QIlxQ==/lib/arm64'
07-01 09:53:43.078 31344 31396 D vulkan  : searching for layers in '/data/app/~~28i-LXFSmsgbhQ6GFnrqOw==/org.nekomanga.neko-2qI4gdaDIBkZWWf86QIlxQ==/base.apk!/lib/arm64-v8a'
07-01 09:53:43.080 31344 31344 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
07-01 09:53:43.089 31344 31344 D CompatibilityChangeReporter: Compat change id reported: 279646685; UID 10404; state: DISABLED
07-01 09:53:43.101 31344 31344 I ContentCaptureHelper: Setting logging level to OFF
07-01 09:53:43.105 31344 31344 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10404; state: DISABLED
07-01 09:53:43.119 31344 31344 E SQLiteLog: (283) recovered 130 frames from WAL file /data/data/org.nekomanga.neko/databases/tachiyomi.db-wal
07-01 09:53:43.162 31344 31344 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10404; state: ENABLED
07-01 09:53:50.334 31344 31344 D CompatibilityChangeReporter: Compat change id reported: 258825825; UID 10404; state: ENABLED
07-01 09:53:53.550 31344 31353 I o:error_handler: Background concurrent mark compact GC freed 182221(12MB) AllocSpace objects, 30(1800KB) LOS objects, 83% free, 4738KB/28MB, paused 733us,3.810ms total 100.242ms
07-01 09:53:53.555 31344 31355 W o:error_handler: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/base.apk' with 1 weak references
07-01 09:53:53.555 31344 31355 W o:error_handler: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/split_config.en.apk' with 1 weak references
07-01 09:53:53.555 31344 31355 W o:error_handler: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/split_config.fr.apk' with 1 weak references
07-01 09:53:53.555 31344 31355 W o:error_handler: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~pYQCJZhsdSk2woDBWuNHfg==/com.google.android.trichromelibrary_647813433-GaBJyiSwFS3ym1QTjrme0Q==/base.apk' with 1 weak references
07-01 09:54:38.306 31344 31344 D SCViewSupport: screenshot.scroll_capture_delay = 60
07-01 09:54:42.617 31344 31344 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10404; state: ENABLED
07-01 09:54:45.889 31565 31565 I .nekomanga.neko: Using CollectorTypeCMC GC.
07-01 09:54:45.893 31565 31565 E .nekomanga.neko: Not starting debugger since process cannot load the jdwp agent.
07-01 09:54:45.906 31565 31565 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10404; state: ENABLED
07-01 09:54:45.906 31565 31565 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10404; state: ENABLED
07-01 09:54:45.923 31565 31565 D nativeloader: Configuring clns-4 for other apk /data/app/~~28i-LXFSmsgbhQ6GFnrqOw==/org.nekomanga.neko-2qI4gdaDIBkZWWf86QIlxQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~28i-LXFSmsgbhQ6GFnrqOw==/org.nekomanga.neko-2qI4gdaDIBkZWWf86QIlxQ==/lib/arm64:/data/app/~~28i-LXFSmsgbhQ6GFnrqOw==/org.nekomanga.neko-2qI4gdaDIBkZWWf86QIlxQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/org.nekomanga.neko
07-01 09:54:45.932 31565 31565 I MultiDex: VM with version 2.1.0 has multidex support
07-01 09:54:45.932 31565 31565 I MultiDex: Installing application
07-01 09:54:45.932 31565 31565 I MultiDex: VM has multidex support, MultiDex support library is disabled.
07-01 09:54:45.936 31565 31565 D CompatibilityChangeReporter: Compat change id reported: 183155436; UID 10404; state: ENABLED
07-01 09:54:45.937 31565 31565 D SessionsDependencies: Dependency to CRASHLYTICS added.
07-01 09:54:45.938 31565 31565 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
07-01 09:54:45.942 31565 31565 D FirebaseSessions: Initializing Firebase Sessions SDK.
07-01 09:54:45.945 31565 31565 I FirebaseCrashlytics: Initializing Firebase Crashlytics 19.0.2 for org.nekomanga.neko
07-01 09:54:45.949 31565 31565 D SessionsDependencies: Subscriber CRASHLYTICS registered.
07-01 09:54:45.955 31565 31602 D LifecycleServiceBinder: Binding service to application.
07-01 09:54:45.958 31565 31565 I FirebaseInitProvider: FirebaseApp initialization successful
07-01 09:54:45.958 31565 31565 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
07-01 09:54:45.959 31565 31565 D WM-PackageManagerHelper: Skipping component enablement for androidx.work.impl.background.systemjob.SystemJobService
07-01 09:54:45.959 31565 31565 D WM-Schedulers: Created SystemJobScheduler and enabled SystemJobService
07-01 09:54:45.960 31565 31601 I DynamiteModule: Considering local module com.google.android.gms.measurement.dynamite:117 and remote module com.google.android.gms.measurement.dynamite:115
07-01 09:54:45.960 31565 31601 I DynamiteModule: Selected local version of com.google.android.gms.measurement.dynamite
07-01 09:54:45.962 31565 31565 D CompatibilityChangeReporter: Compat change id reported: 279646685; UID 10404; state: DISABLED
07-01 09:54:45.964 31565 31603 I FirebaseCrashlytics: No version control information found
07-01 09:54:45.969 31565 31565 W ziparchive: Unable to open '/data/app/~~pYQCJZhsdSk2woDBWuNHfg==/com.google.android.trichromelibrary_647813433-GaBJyiSwFS3ym1QTjrme0Q==/base.dm': No such file or directory
07-01 09:54:45.969 31565 31565 W ziparchive: Unable to open '/data/app/~~pYQCJZhsdSk2woDBWuNHfg==/com.google.android.trichromelibrary_647813433-GaBJyiSwFS3ym1QTjrme0Q==/base.dm': No such file or directory
07-01 09:54:45.970 31565 31565 W .nekomanga.neko: Entry not found
07-01 09:54:45.971 31565 31565 D nativeloader: Configuring clns-5 for other apk /data/app/~~pYQCJZhsdSk2woDBWuNHfg==/com.google.android.trichromelibrary_647813433-GaBJyiSwFS3ym1QTjrme0Q==/base.apk. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/lib/arm64:/data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/base.apk!/lib/arm64-v8a:/data/app/~~pYQCJZhsdSk2woDBWuNHfg==/com.google.android.trichromelibrary_647813433-GaBJyiSwFS3ym1QTjrme0Q==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
07-01 09:54:45.971 31565 31565 D nativeloader: Extending system_exposed_libraries: libedgetpu_dba.google.so
07-01 09:54:45.975 31565 31565 D nativeloader: Configuring clns-6 for other apk /data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/lib/arm64:/data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/base.apk!/lib/arm64-v8a:/data/app/~~pYQCJZhsdSk2woDBWuNHfg==/com.google.android.trichromelibrary_647813433-GaBJyiSwFS3ym1QTjrme0Q==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
07-01 09:54:45.978 31565 31565 I WebViewFactory: Loading com.google.android.webview version 126.0.6478.134 (code 647813433)
07-01 09:54:45.982 31565 31614 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10404; state: ENABLED
07-01 09:54:45.988 31565 31614 D CompatibilityChangeReporter: Compat change id reported: 194532703; UID 10404; state: ENABLED
07-01 09:54:45.988 31565 31614 D CompatibilityChangeReporter: Compat change id reported: 253665015; UID 10404; state: ENABLED
07-01 09:54:45.988 31565 31614 D CompatibilityChangeReporter: Compat change id reported: 311402873; UID 10404; state: DISABLED
07-01 09:54:45.988 31565 31614 D CompatibilityChangeReporter: Compat change id reported: 323349338; UID 10404; state: DISABLED
07-01 09:54:45.988 31565 31565 I cr_WVCFactoryProvider: version=126.0.6478.134 (647813433) minSdkVersion=29 isBundle=true multiprocess=true packageId=2
07-01 09:54:45.990 31565 31616 I FA      : App measurement initialized, version: 97001
07-01 09:54:45.991 31565 31616 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
07-01 09:54:45.991 31565 31616 I FA      : To enable faster debug mode event logging run:
07-01 09:54:45.991 31565 31616 I FA      :   adb shell setprop debug.firebase.analytics.app org.nekomanga.neko
07-01 09:54:45.995 31565 31622 E chromium: [0701/095445.994743:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
07-01 09:54:45.999 31565 31565 I cr_LibraryLoader: Successfully loaded native library
07-01 09:54:46.000 31565 31565 I cr_CachingUmaRecorder: Flushed 6 samples from 6 histograms, 0 samples were dropped.
07-01 09:54:46.042 31565 31565 D SessionLifecycleService: Service bound to new client on process 31565
07-01 09:54:46.042 31565 31634 D SessionLifecycleService: App has not yet foregrounded. Using previously stored session: null
07-01 09:54:46.042 31565 31634 D SessionLifecycleService: Client android.os.Messenger@b042e06 bound at 196167610. Clients: 1
07-01 09:54:46.053 31565 31635 I TRuntime.CctTransportBackend: Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
07-01 09:54:46.070 31565 31565 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
07-01 09:54:46.071 31565 31565 W SQLiteConnection: Could not change the database journal mode of '/data/user/0/org.nekomanga.neko/databases/tachiyomi.db' from 'wal' to 'TRUNCATE' because the database is locked.  This usually means that there are other open connections to the database which prevents the database from enabling or disabling write-ahead logging mode.  Proceeding without changing the journal mode.
07-01 09:54:46.077 31565 31565 D SessionLifecycleClient: Connected to SessionLifecycleService. Queue size 0
07-01 09:54:46.078 31565 31635 D TrafficStats: tagSocket(109) with statsTag=0xffffffff, statsUid=-1
07-01 09:54:47.697 31565 31635 I TRuntime.CctTransportBackend: Status Code: 200
07-01 09:54:51.146 31565 31831 D ProfileInstaller: Skipping profile installation for org.nekomanga.neko
07-01 09:54:53.871 31344 31344 D VRI[CrashActivity]: visibilityChanged oldVisibility=true newVisibility=false
07-01 09:55:13.119 31565 31579 W .nekomanga.neko: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/base.apk' with 1 weak references
07-01 09:55:13.120 31565 31579 W .nekomanga.neko: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/split_config.en.apk' with 1 weak references
07-01 09:55:13.120 31565 31579 W .nekomanga.neko: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~LcAz8Xk-4cd006YvydKe5g==/com.google.android.webview-uJGy29qgvzypoIQ_n9IP6A==/split_config.fr.apk' with 1 weak references
07-01 09:55:13.120 31565 31579 W .nekomanga.neko: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~pYQCJZhsdSk2woDBWuNHfg==/com.google.android.trichromelibrary_647813433-GaBJyiSwFS3ym1QTjrme0Q==/base.apk' with 1 weak references

### Neko version

2.16.9

### Android version

14

### Device

Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by TheTabbingman** [comment]
#1861
