### ISSUE TITLE
Instant crash when selecting search on Browse tab.

### ISSUE THREAD

**Issue by FuristicW** [nekomangaorg/Neko#1874]
### Steps to reproduce

Open app, press browse, press search. 
![Screenshot_20240701_192757](https://github.com/nekomangaorg/Neko/assets/67134310/b08044c4-1b7c-4b94-8bfc-4405f33ea998)

### Expected behavior

It shouldn't crash

### Actual behavior

It crashes

### Crash logs

App version: 2.16.9 (standard, b6d958781, 10, 2024-06-28T00:51:12.841592104)
Android version: 14 (SDK 34)
Android build ID: UP1A.231005.007.S928U1UES2AXE4
Device brand: samsung
Device manufacturer: samsung
Device name: e3q
Device model: SM-S928U1
Device product name: e3quew
           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: kotlinx.serialization.SerializationException: eu.kanade.tachiyomi.source.model.MangaTag does not contain element with name 'ECCHI' at path $.tags[16].tag
at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow(Unknown Source:63)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeEnum(Unknown Source:33)
at kotlinx.serialization.internal.EnumSerializer.deserialize(SourceFile:1)
at kotlinx.serialization.internal.EnumSerializer.deserialize(SourceFile:2)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(Unknown Source:119)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(Unknown Source:10)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:32)
at org.nekomanga.domain.filter.Filter$Tag$$serializer.deserialize(SourceFile:3)
at org.nekomanga.domain.filter.Filter$Tag$$serializer.deserialize(SourceFile:1)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(Unknown Source:119)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(Unknown Source:10)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:32)
at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Unknown Source:7)
at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(Unknown Source:17)
at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(Unknown Source:7)
at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(Unknown Source:63)
at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(Unknown Source:6)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(Unknown Source:119)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(Unknown Source:10)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:32)
at org.nekomanga.domain.filter.DexFilters$$serializer.deserialize(SourceFile:3)
at org.nekomanga.domain.filter.DexFilters$$serializer.deserialize(SourceFile:1)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(Unknown Source:119)
at kotlinx.serialization.json.Json.decodeFromString(SourceFile:2)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1$nameOfEnabledFilter$2.invoke(SourceFile:2)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1$nameOfEnabledFilter$2.invoke(SourceFile:3)
at coil.size.-Sizes.rememberSaveable(SourceFile:87)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1.invoke(SourceFile:19)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
at coil.request.Svgs.CompositionLocalProvider(SourceFile:24)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt.FilterBrowseSheet-gKLzdoI(SourceFile:2)
at org.nekomanga.presentation.screens.browse.BrowseBottomSheetKt.BrowseBottomSheet(SourceFile:460)
at org.nekomanga.presentation.screens.BrowseScreenKt$BrowseScreen$4$1.invoke(SourceFile:22)
at org.nekomanga.presentation.screens.BrowseScreenKt$BrowseScreen$4$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:3)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:14)
at androidx.compose.material.ScaffoldKt$Scaffold$1.invoke(SourceFile:22)
at androidx.compose.material.ScaffoldKt$Scaffold$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:85)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(SourceFile:49)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(SourceFile:2)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
at ColumnHeaderKt$$ExternalSyntheticOutline0.m(SourceFile:73)
at coil.request.Svgs.CompositionLocalProvider(SourceFile:47)
at coil.size.-Sizes.Surface-F-jzlyU(SourceFile:373)
at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$2.invoke(SourceFile:406)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:3)
at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(SourceFile:36)
at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(SourceFile:4)
at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(SourceFile:490)
at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(SourceFile:58)
at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:156)
at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(SourceFile:29)
at androidx.compose.runtime.CompositionImpl.recompose(SourceFile:34)
at androidx.compose.runtime.Recomposer.access$performRecompose(SourceFile:100)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(SourceFile:404)
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(Unknown Source:8)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(SourceFile:48)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
at android.view.Choreographer.doFrame(Choreographer.java:1069)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8918)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@2031313, androidx.compose.ui.platform.MotionDurationScaleImpl@ed11950, StandaloneCoroutine{Cancelling}@89e5749, AndroidUiDispatcher@579984e]

           ******************************************************************************************************************************************************************************************************************************
           ******************************************************************************************************************************************************************************************************************************--------- beginning of main
07-01 19:25:48.251 20919 20919 I ViewRootImpl@28cb205[MainActivity]: ViewPostIme pointer 0
07-01 19:25:48.252 20919 20919 I GestureDetector: obtain mCurrentDownEvent. id: 293971093 caller: eu.kanade.tachiyomi.ui.main.MainActivity.dispatchTouchEvent:10 androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchTouchEvent:3 com.android.internal.policy.DecorView.dispatchTouchEvent:740 
07-01 19:25:48.263 20919 20919 I GestureDetector: obtain mCurrentMotionEventRaw. action: 2 id: 504966153
07-01 19:25:48.342 20919 20919 I ViewRootImpl@28cb205[MainActivity]: ViewPostIme pointer 1
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: A problem occurred while reading the Crashlytics log file.
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: java.io.EOFException
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at java.io.RandomAccessFile.readInt(RandomAccessFile.java:891)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.metadata.QueueFile.readElement(Unknown Source:13)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.metadata.QueueFile.forEach(Unknown Source:10)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.metadata.QueueFileLogStore.getLogAsString(SourceFile:40)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at com.caverock.androidsvg.RenderOptions.addLogsAndCustomKeysToEvent(SourceFile:7)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at com.caverock.androidsvg.RenderOptions.persistEvent(SourceFile:493)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$6.run(SourceFile:65)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at androidx.work.impl.model.WorkSpecDao_Impl$23.call(SourceFile:38)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at com.airbnb.lottie.model.MutablePair.then(SourceFile:1)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at com.google.android.gms.tasks.zzc.run(SourceFile:1023)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(Unknown Source:2)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(Unknown Source:5)
07-01 19:25:48.369 20919 20946 E FirebaseCrashlytics: 	at java.lang.Thread.run(Thread.java:1012)
07-01 19:25:48.376 20919 20919 I .nekomanga.neko: System.exit called, status: 0
07-01 19:25:48.376 20919 20919 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
07-01 19:25:48.460 14405 14405 I o:error_handler: Using CollectorTypeCC GC.
07-01 19:25:48.462 14405 14405 E o:error_handler: Not starting debugger since process cannot load the jdwp agent.
07-01 19:25:48.465 14405 14405 D ActivityThread: setConscryptValidator
07-01 19:25:48.465 14405 14405 D ActivityThread: setConscryptValidator - put
07-01 19:25:48.473 14405 14405 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10413; state: ENABLED
07-01 19:25:48.473 14405 14405 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10413; state: ENABLED
07-01 19:25:48.488 14405 14405 D nativeloader: Configuring clns-4 for other apk /data/app/~~ilH5hqJPkMNNq51Y_M3dvg==/org.nekomanga.neko-FayjR-0c7U-mu0m-O4RaOg==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~ilH5hqJPkMNNq51Y_M3dvg==/org.nekomanga.neko-FayjR-0c7U-mu0m-O4RaOg==/lib/arm64:/data/app/~~ilH5hqJPkMNNq51Y_M3dvg==/org.nekomanga.neko-FayjR-0c7U-mu0m-O4RaOg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/org.nekomanga.neko
07-01 19:25:48.494 14405 14405 I MultiDex: VM with version 2.1.0 has multidex support
07-01 19:25:48.494 14405 14405 I MultiDex: Installing application
07-01 19:25:48.494 14405 14405 I MultiDex: VM has multidex support, MultiDex support library is disabled.
07-01 19:25:48.496 14405 14405 W ziparchive: Unable to open '/data/app/~~7aS6ITYXCFpF_Dz7mAWr0w==/com.google.android.trichromelibrary_647813333-Xp-WHsXPxRWLzu1ydIzBtA==/base.dm': No such file or directory
07-01 19:25:48.496 14405 14405 W ziparchive: Unable to open '/data/app/~~7aS6ITYXCFpF_Dz7mAWr0w==/com.google.android.trichromelibrary_647813333-Xp-WHsXPxRWLzu1ydIzBtA==/base.dm': No such file or directory
07-01 19:25:48.496 14405 14405 W o:error_handler: Entry not found
07-01 19:25:48.496 14405 14405 D nativeloader: Configuring clns-5 for other apk /data/app/~~7aS6ITYXCFpF_Dz7mAWr0w==/com.google.android.trichromelibrary_647813333-Xp-WHsXPxRWLzu1ydIzBtA==/base.apk. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~vAt2jjJRCpU45VfKFUkKaw==/com.google.android.webview-RMAVjnCdIRilu7ayU3x9lQ==/lib/arm64:/data/app/~~vAt2jjJRCpU45VfKFUkKaw==/com.google.android.webview-RMAVjnCdIRilu7ayU3x9lQ==/base.apk!/lib/arm64-v8a:/data/app/~~7aS6ITYXCFpF_Dz7mAWr0w==/com.google.android.trichromelibrary_647813333-Xp-WHsXPxRWLzu1ydIzBtA==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
07-01 19:25:48.496 14405 14405 D nativeloader: Extending system_exposed_libraries: libhumantracking.arcsoft.so:libPortraitDistortionCorrection.arcsoft.so:libPortraitDistortionCorrectionCali.arcsoft.so:libface_landmark.arcsoft.so:libFacialStickerEngine.arcsoft.so:libfrtracking_engine.arcsoft.so:libFaceRecognition.arcsoft.so:libveengine.arcsoft.so:lib_pet_detection.arcsoft.so:libae_bracket_hdr.arcsoft.so:libdigital_tele_scope.arcsoft.so:libdigital_tele_scope_rawsr.arcsoft.so:libsf_tetra_enhance.arcsoft.so:libhybrid_high_dynamic_range.arcsoft.so:libimage_enhancement.arcsoft.so:liblow_light_hdr.arcsoft.so:libmacroclearshot_raw.arcsoft.so:libhigh_dynamic_range.arcsoft.so:libsuperresolution_raw.arcsoft.so:libobjectcapture_jni.arcsoft.so:libobjectcapture.arcsoft.so:libFacialAttributeDetection.arcsoft.so:libaudiomirroring_jni.audiomirroring.samsung.so:libBeauty_v4.camera.samsung.so:libexifa.camera.samsung.so:libjpega.camera.samsung.so:libOpenCv.camera.samsung.so:libaifrcInterface.camera.samsung.so:libVideoClassifier.camera.samsung.so:libImageScreener.camera.sams
07-01 19:25:48.497 14405 14405 D nativeloader: Configuring clns-6 for other apk /data/app/~~vAt2jjJRCpU45VfKFUkKaw==/com.google.android.webview-RMAVjnCdIRilu7ayU3x9lQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~vAt2jjJRCpU45VfKFUkKaw==/com.google.android.webview-RMAVjnCdIRilu7ayU3x9lQ==/lib/arm64:/data/app/~~vAt2jjJRCpU45VfKFUkKaw==/com.google.android.webview-RMAVjnCdIRilu7ayU3x9lQ==/base.apk!/lib/arm64-v8a:/data/app/~~7aS6ITYXCFpF_Dz7mAWr0w==/com.google.android.trichromelibrary_647813333-Xp-WHsXPxRWLzu1ydIzBtA==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
07-01 19:25:48.499 14405 14405 I WebViewFactory: Loading com.google.android.webview version 126.0.6478.133 (code 647813333)
07-01 19:25:48.508 14405 14405 I cr_WVCFactoryProvider: version=126.0.6478.133 (647813333) minSdkVersion=29 isBundle=true multiprocess=true packageId=2
07-01 19:25:48.513 14405 14435 E chromium: [0701/192548.513482:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
07-01 19:25:48.515 14405 14405 I cr_LibraryLoader: Successfully loaded native library
07-01 19:25:48.515 14405 14405 I cr_CachingUmaRecorder: Flushed 6 samples from 6 histograms, 0 samples were dropped.
07-01 19:25:48.552 14405 14405 W Iconics : At least one font needs to be registered first
07-01 19:25:48.552 14405 14405 W Iconics :     via com.mikepenz.iconics.Iconics.registerFont(Iconics.kt:117)
07-01 19:25:48.560 14405 14405 D OpenGLRenderer: HWUI - treat SMPTE_170M as sRGB
07-01 19:25:48.563 14405 14405 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
07-01 19:25:48.563 14405 14463 I AdrenoGLES-0: QUALCOMM build                   : d774a8672e, I8ea610b5b4
07-01 19:25:48.563 14405 14463 I AdrenoGLES-0: Build Date                       : 01/03/24
07-01 19:25:48.563 14405 14463 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: E031.42.23.12
07-01 19:25:48.563 14405 14463 I AdrenoGLES-0: Local Branch                     : 
07-01 19:25:48.563 14405 14463 I AdrenoGLES-0: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.VENDOR.14.3.0.11.00.00.973.408
07-01 19:25:48.563 14405 14463 I AdrenoGLES-0: Remote Branch                    : NONE
07-01 19:25:48.563 14405 14463 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
07-01 19:25:48.563 14405 14463 I AdrenoGLES-0: Build Config                     : S P 16.1.2 AArch64
07-01 19:25:48.563 14405 14463 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
07-01 19:25:48.563 14405 14463 I AdrenoGLES-0: Driver Version                   : 0744.18
07-01 19:25:48.563 14405 14463 I AdrenoGLES-0: Process Name                     : org.nekomanga.neko:error_handler
07-01 19:25:48.566 14405 14463 I AdrenoGLES-0: PFP: 0x01520171, ME: 0x01520023
07-01 19:25:48.568 14405 14463 E Adreno-AppProfiles: QSPM AIDL service doesn't exist
07-01 19:25:48.570 14405 14463 I AdrenoUtils: <ReadGpuID:353>: Reading chip ID through GSL
07-01 19:25:48.573 14405 14405 I DecorView: setWindowBackground: isPopOver=false color=ff16151d d=android.graphics.drawable.ColorDrawable@6ed8e09
07-01 19:25:48.577 14405 14405 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10413; state: DISABLED
07-01 19:25:48.578 14405 14405 W libc    : Access denied finding property "persist.dm.passive.display_brightness"
07-01 19:25:48.578 14405 14405 W libc    : Access denied finding property "persist.dm.passive.ambient_brightness"
07-01 19:25:48.578 14405 14463 D NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
07-01 19:25:48.584 14405 14405 I InsetsController: onStateChanged: host=org.nekomanga.neko/eu.kanade.tachiyomi.crash.CrashActivity, from=android.view.ViewRootImpl.setView:1751, state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2340), mDisplayCutout=DisplayCutout{insets=Rect(0, 76 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(515, 0 - 565, 76), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2340 physicalDisplayWidth=1080 physicalDisplayHeight=2340 density={2.8125} cutoutSpec={M 0,0 H -8.933333333333333 V 26.93333333333333 H 8.933333333333333 V 0 H 0 Z @dp} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=5, center=Point(5, 5)}, RoundedCorner{position=TopRight, radius=5, center=Point(1075, 5)}, RoundedCorner{position=BottomRight, radius=5, center=Point(1075, 2335)}, RoundedCorner{position=BottomLeft, radius=5, center=Point(5, 2335)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2340), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(956, 0 - 1080, 76) rotation=0}, mDisplayShape=DisplayShape{ spec=-1951251426 displayWidth=1440 displayHeight=3120 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {3 mType=ime mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {27 mType=displayCutout mFrame=[0,0][1080,76] mVisible=true mFlags=[]}, InsetsSource: {4f850000 mType=statusBars mFrame=[0,0][1080,76] mVisible=true mFlags=[]}, InsetsSource: {4f850005 mType=mandatorySystemGestures mFrame=[0,0][1080,110] mVisible=true mFlags=[]}, InsetsSource: {4f850006 mType=tappableElement mFrame=[0,0][1080,76] mVisible=true mFlags=[]}, InsetsSource: {5ef40001 mType=navigationBars mFrame=[0,2205][1080,2340] mVisible=true mFlags=[]}, InsetsSource: {5ef40004 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {5ef40005 mType=mandatorySystemGestures mFrame=[0,2205][1080,2340] mVisible=true mFlags=[]}, InsetsSource: {5ef40006 mType=tappableElement mFrame=[0,2205][1080,2340] mVisible=true mFlags=[]}, InsetsSource: {5ef40024 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]} }
07-01 19:25:48.584 14405 14405 I ViewRootImpl@c990b79[CrashActivity]: synced displayState. AttachInfo displayState=2
07-01 19:25:48.584 14405 14405 I ViewRootImpl@c990b79[CrashActivity]: setView = com.android.internal.policy.DecorView@c15e635 TM=true
07-01 19:25:48.584 14405 14405 I IDS_TAG : Starting IDS observe window
07-01 19:25:48.584 14405 14405 I IDS_TAG : Getting Shared Preference for org.nekomanga.App@1f11599 uid = 10413
07-01 19:25:48.585 14405 14405 I IDS_TAG : App org.nekomanga.App@1f11599 has not finished training
07-01 19:25:48.669 14405 14463 D OpenGLRenderer: HWUI - treat SMPTE_170M as sRGB
07-01 19:25:48.669 14405 14405 I IDS_TAG : Closing IDS observe window
07-01 19:25:48.669 14405 14405 I IDS_TAG : Getting Shared Preference for org.nekomanga.App@1f11599 uid = 10413
07-01 19:25:48.669 14405 14405 I 

### Neko version

2.16.9

### Android version

Android 14

### Device

Samsung S24 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by TheTabbingman** [comment]
#1861
