### ISSUE TITLE
Neko won't update to latest version (2.16.9)

### ISSUE THREAD

**Issue by Yoposoc** [nekomangaorg/Neko#1889]
### Steps to reproduce

Try to update, and then it fails saying "app not installed." 

### Expected behavior

App updates. 

### Actual behavior

Fails with error message mentioned above. 

### Crash logs

com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor$BadContentProviderException: DISPLAY_NAME column is null
	at com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor.name(ContentUriFileDescriptor.java:30)
	at com.aefyr.sai.model.apksource.DefaultApkSource.getApkLocalPath(DefaultApkSource.java:47)
	at com.aefyr.sai.model.apksource.FilterApkSource.getApkLocalPath(FilterApkSource.java:60)
	at com.aefyr.sai.model.apksource.FilterApkSource.nextApk(FilterApkSource.java:28)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:93)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:70)
	at com.aefyr.sai.installer2.impl.rootless.-$$Lambda$RootlessSaiPackageInstaller$ivyAcunEgIkYlu_dB2vN6MOWZPU.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
	

### Neko version

2.16.7

### Android version

Android 8.0

### Device

Samsung galaxy tab S3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Sounds like an issue with SAI.  As you are using a third party installer.  Have you tried manually updating from github?

**Comment by Yoposoc** [comment]
I tried using the regular android package installer, and get the "app not installed" error. Both through the popup on startup of Neko, as well as when manually trying out the apk downloaded off github. I can confirm it still happens now for 2.16.10.

**Comment by Yoposoc** [comment]
It was not working up to the most recent version. Somehow got it working the other day. Not sure what the issue was, but I think it is related to free storage size, and making sure to fully close down the app before trying again. Hope that helps anyone else.
