### ISSUE TITLE
App crashes on pressing search

### ISSUE THREAD

**Issue by WilfridSM** [nekomangaorg/Neko#1993]
### Steps to reproduce

Select the browse tab, press search.

### Expected behavior

Search menu appears.

### Actual behavior

"An unexpected error occurred"

### Crash logs

pp version: 2.18.2 (standard, b922d2838, 16, 2024-11-27T01:16:06.20432505)
Android version: 14 (SDK 34)
Android build ID: UP1A.231005.007.G991BXXSDGXI5
Device brand: samsung
Device manufacturer: samsung
Device name: o1s
Device model: SM-G991B
Device product name: o1sxeea           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: kotlinx.serialization.SerializationException: eu.kanade.tachiyomi.source.online.utils.MdLang does not contain element with name 'LINTHUANIAN' at path $.originalLanguage[29].language
at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow(SourceFile:64)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeEnum(SourceFile:34)
at kotlinx.serialization.internal.EnumSerializer.deserialize(SourceFile:2)
at kotlinx.serialization.internal.EnumSerializer.deserialize(SourceFile:1)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(SourceFile:314)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(SourceFile:11)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:33)
at org.nekomanga.domain.filter.Filter$OriginalLanguage$$serializer.deserialize(SourceFile:4)
at org.nekomanga.domain.filter.Filter$OriginalLanguage$$serializer.deserialize(SourceFile:1)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(SourceFile:314)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(SourceFile:11)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:33)
at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(SourceFile:8)
at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(SourceFile:18)
at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(SourceFile:8)
at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(SourceFile:64)
at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(SourceFile:7)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(SourceFile:314)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(SourceFile:11)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:33)
at org.nekomanga.domain.filter.DexFilters$$serializer.deserialize(SourceFile:4)
at org.nekomanga.domain.filter.DexFilters$$serializer.deserialize(SourceFile:1)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(SourceFile:314)
at kotlinx.serialization.json.Json.decodeFromString(SourceFile:4)
at eu.kanade.tachiyomi.AppModule$$ExternalSyntheticLambda6.invoke(SourceFile:183)
at ColumnHeaderKt.rememberSaveable(SourceFile:76)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1.invoke(SourceFile:43)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
at androidx.compose.runtime.AnchoredGroupPath.CompositionLocalProvider(SourceFile:77)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt.FilterBrowseSheet-gKLzdoI(SourceFile:9)
at org.nekomanga.presentation.screens.browse.BrowseBottomSheetKt.BrowseBottomSheet(SourceFile:431)
at org.nekomanga.presentation.screens.BrowseScreenKt$BrowseScreen$4$1.invoke(SourceFile:38)
at org.nekomanga.presentation.screens.BrowseScreenKt$BrowseScreen$4$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:35)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:10)
at androidx.compose.material3.CardKt$Card$1.invoke(SourceFile:386)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(SourceFile:411)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
at androidx.compose.runtime.AnchoredGroupPath.CompositionLocalProvider(SourceFile:28)
at androidx.core.math.MathUtils.Surface-F-jzlyU(SourceFile:270)
at androidx.compose.material.ModalBottomSheetKt.ModalBottomSheetLayout-Gs3lGvM(SourceFile:740)
at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$2.invoke(SourceFile:42)
at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(SourceFile:451)
at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(SourceFile:137)
at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:244)
at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(SourceFile:30)
at androidx.compose.runtime.CompositionImpl.recompose(SourceFile:23)
at androidx.compose.runtime.Recomposer.access$performRecompose(SourceFile:114)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(SourceFile:584)
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(SourceFile:48)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(SourceFile:48)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
at android.view.Choreographer.doFrame(Choreographer.java:1069)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8919)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@480483c, androidx.compose.ui.platform.MotionDurationScaleImpl@b0939c5, StandaloneCoroutine{Cancelling}@5e5cf1a, AndroidUiDispatcher@f4a4b]

### Neko version

2.18.2

### Android version

Android 14

### Device

Samsung Galaxy S21

### Other details

I have a suspicion that this bug may be related to the number of manga I have (currently 1507).

I only noticed this bug after the last update.

The crash log is too long to include the full version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Clear search filters in mangadex settings

**Comment by WilfridSM** [comment]
Worked, thank you.
