### ISSUE TITLE
Search function crashes client due to a Lithuanian serialization exception.

### ISSUE THREAD

**Issue by AwdBawl** [nekomangaorg/Neko#2003]
### Steps to reproduce

1) Enter browse homepage.
2) Press search button.

### Expected behavior

Search button SHOULD bring up the filter prompt.

### Actual behavior

Client crashes. Generates crash log mentioning a serialization exception involving the Lithuanian language (or the lack thereof).

### Crash logs

App version: 2.18.2 (standard, b922d2838, 16, 2024-11-27T01:16:06.20432505)
Android version: 14 (SDK 34)
Android build ID: TB370FU_ROW_OPEN_USER_V15.125_U_ZUI_16.0.177_ST_240912
Device brand: Lenovo
Device manufacturer: LENOVO
Device name: TB370FU
Device model: TB370FU
Device product name: TB370FU           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: kotlinx.serialization.SerializationException: eu.kanade.tachiyomi.source.online.utils.MdLang does not contain element with name 'LINTHUANIAN' at path $.originalLanguage[29].language
at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow(SourceFile:64)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeEnum(SourceFile:34)
at kotlinx.serialization.internal.EnumSerializer.deserialize(SourceFile:2)
at kotlinx.serialization.internal.EnumSerializer.deserialize(SourceFile:1)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(SourceFile:314)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(SourceFile:11)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:33)
at org.nekomanga.domain.filter.Filter$OriginalLanguage$$serializer.deserialize(SourceFile:4)
at org.nekomanga.domain.filter.Filter$OriginalLanguage$$serializer.deserialize(SourceFile:1)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(SourceFile:314)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(SourceFile:11)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:33)
at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(SourceFile:8)
at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(SourceFile:18)
at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(SourceFile:8)
at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(SourceFile:64)
at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(SourceFile:7)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(SourceFile:314)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(SourceFile:2)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(SourceFile:11)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:33)
at org.nekomanga.domain.filter.DexFilters$$serializer.deserialize(SourceFile:4)
at org.nekomanga.domain.filter.DexFilters$$serializer.deserialize(SourceFile:1)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(SourceFile:314)
at kotlinx.serialization.json.Json.decodeFromString(SourceFile:4)
at eu.kanade.tachiyomi.AppModule$$ExternalSyntheticLambda6.invoke(SourceFile:183)
at ColumnHeaderKt.rememberSaveable(SourceFile:76)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1.invoke(SourceFile:43)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt$FilterBrowseSheet$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
at androidx.compose.runtime.AnchoredGroupPath.CompositionLocalProvider(SourceFile:77)
at org.nekomanga.presentation.components.sheets.FilterBrowseSheetKt.FilterBrowseSheet-gKLzdoI(SourceFile:9)
at org.nekomanga.presentation.screens.browse.BrowseBottomSheetKt.BrowseBottomSheet(SourceFile:431)
at org.nekomanga.presentation.screens.BrowseScreenKt$BrowseScreen$4$1.invoke(SourceFile:38)
at org.nekomanga.presentation.screens.BrowseScreenKt$BrowseScreen$4$1.invoke(SourceFile:1)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:35)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:10)
at androidx.compose.material3.CardKt$Card$1.invoke(SourceFile:386)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
at androidx.compose.material.SurfaceKt$Surface$1.invoke(SourceFile:411)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
at androidx.compose.runtime.AnchoredGroupPath.CompositionLocalProvider(SourceFile:28)
at androidx.core.math.MathUtils.Surface-F-jzlyU(SourceFile:270)
at androidx.compose.material.ModalBottomSheetKt.ModalBottomSheetLayout-Gs3lGvM(SourceFile:740)
at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$2.invoke(SourceFile:42)
at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(SourceFile:451)
at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(SourceFile:137)
at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:244)
at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(SourceFile:30)
at androidx.compose.runtime.CompositionImpl.recompose(SourceFile:23)
at androidx.compose.runtime.Recomposer.access$performRecompose(SourceFile:114)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(SourceFile:584)
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(SourceFile:48)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(SourceFile:48)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1748)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1759)
at android.view.Choreographer.doCallbacks(Choreographer.java:1333)
at android.view.Choreographer.doFrame(Choreographer.java:1223)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1733)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:206)
at android.os.Looper.loop(Looper.java:295)
at android.app.ActivityThread.main(ActivityThread.java:8733)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1053)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@b415feb, androidx.compose.ui.platform.MotionDurationScaleImpl@d1a148, StandaloneCoroutine{Cancelling}@e15cbe1, AndroidUiDispatcher@46c8d06]

           ******************************************************************************************************************************************************************************************************************************
           ******************************************************************************************************************************************************************************************************************************
--------- beginning of system
12-19 00:08:46.303 29398 29398 D WindowManagerImpl: addView displayId=0 0
12-19 00:08:46.303 29398 29398 D WindowManagerImpl: addView displayId33= 0
12-19 00:08:46.305 29398 29398 D SystemServiceRegistry:  zuiHandwriting new zuihandwritingmanager
12-19 00:08:48.252 29398 29398 D WindowManagerImpl: addView displayId=0 0
12-19 00:08:48.252 29398 29398 D WindowManagerImpl: addView displayId33= 0
12-19 00:09:41.466 25409 25409 D WindowManagerImpl: addView displayId=0 0
12-19 00:09:41.466 25409 25409 D WindowManagerImpl: addView displayId33= 0
12-19 00:09:41.466 25409 25409 D SystemServiceRegistry:  zuiHandwriting new zuihandwritingmanager
12-19 00:10:18.911 30324 30324 D WindowManagerImpl: addView displayId=0 0
12-19 00:10:18.911 30324 30324 D WindowManagerImpl: addView displayId33= 0
12-19 00:10:18.913 30324 30324 D SystemServiceRegistry:  zuiHandwriting new zuihandwritingmanager
12-19 00:10:20.849 30324 30324 D WindowManagerImpl: addView displayId=0 0
12-19 00:10:20.849 30324 30324 D WindowManagerImpl: addView displayId33= 0
12-19 00:14:34.981 25409 25409 D WindowManagerImpl: addView displayId=0 0
12-19 00:14:34.981 25409 25409 D WindowManagerImpl: addView displayId33= 0
12-19 00:14:34.982 25409 25409 D SystemServiceRegistry:  zuiHandwriting new zuihandwritingmanager
--------- beginning of main
12-19 00:20:02.347 25409 25409 I OvCommonUtils: setFlagsForSplit topActivityComponentInfo{org.nekomanga.neko/eu.kanade.tachiyomi.crash.CrashActivity},  windowMode:1, hasFullScreenFlag:false, isFlagsChanged:false
12-19 00:20:02.365 25409 25409 D BufferQueueConsumer: [](id:63410000000b,api:0,p:-1,c:25409) connect: controlledByApp=false
12-19 00:20:02.366 25409 25431 E OpenGLRenderer: Unable to match the desired swap behavior.
12-19 00:20:02.379 25409 25431 D BLASTBufferQueue: [VRI[CrashActivity]#11](f:0,a:1) acquireNextBufferLocked size=2944x1840 mFrameNumber=1 applyTransaction=true mTimestamp=455711176156463(auto) mPendingTransactions.size=0 graphicBufferId=109130824024116 transform=0

### Neko version

2.18.2

### Android version

Android version: 14 (SDK 34)

### Device

Lenovo Pad P12

### Other details

I'm not filtering for any language in the settings other than English. I've attempted force-stopping the app and clearing the cache, if that matters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Clear your search filters in mangadex settings
